# Generated by Django 5.1.7 on 2025-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a_level_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='o_level_subjects',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
