# Generated by Django 5.1.7 on 2025-04-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_educationhistory_userdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
