# Generated by Django 5.1.7 on 2025-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_institution_logo'),
        ('users', '0006_alter_user_options_user_assigned_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='advanced_preferences',
            field=models.JSONField(default=dict, help_text='Arbitrary advanced preferences for enrollers'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_accept_min_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_accept_programs',
            field=models.ManyToManyField(blank=True, related_name='auto_accept_settings', to='institutions.program'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_assign_reviewer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_reject_criteria',
            field=models.JSONField(default=dict, help_text="Criteria for auto-reject (e.g., {'a_level_points__lt': 5})"),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_review_criteria',
            field=models.JSONField(default=dict, help_text="Criteria for auto-review (e.g., {'o_level_subjects__gte': 5})"),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_reviewer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='enable_auto_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='enable_auto_review',
            field=models.BooleanField(default=False),
        ),
    ]
