# Generated by Django 5.1.7 on 2025-04-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='institution',
        ),
    ]
