# Generated by Django 5.1.7 on 2025-07-03 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_message_notification'),
        ('institutions', '0005_institution_date_established_institution_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='institutions.institution'),
        ),
    ]
