# Generated by Django 5.1.7 on 2025-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_deadline_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='No Subject', max_length=255),
        ),
    ]
