# Generated by Django 5.1.7 on 2025-07-03 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
