# Generated by Django 5.1.7 on 2025-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Transcript', 'Transcript'), ('ID', 'ID'), ('Recommendation Letter', 'Recommendation Letter'), ('others', 'Others')], max_length=100)),
                ('file', models.FileField(upload_to='media/documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
