# Generated by Django 5.1.7 on 2025-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_alter_faculty_code_alter_faculty_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='required_subjects',
            field=models.CharField(default='Mathematics,English', max_length=255),
        ),
    ]
