# Generated by Django 5.1.7 on 2025-06-18 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_institution_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='date_established',
            field=models.DateField(default=datetime.datetime(2025, 6, 18, 10, 55, 1, 429439, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='motto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
